### ISSUE TITLE
"Message published, but not routed"  after publishing Message to argument Exchange

### ISSUE THREAD

**Issue by frickelnix** [thecederick/rabbitmq-arguments-to-headers-exchange#1]
i created an argument exchange and bind a queue to it . if i publishing a message i see an "Message published, but not routed" Dialog in the management interface , but the message is routed to the queue

**Comment by yevhenii-pazii** [comment]
Hi, if you used last build it can be, because of compilation error. Buy you can use version 3.5.6-1.0.3  it is compatible with RabbitMQ 3.6.0 and they work for my. Or you can wait a little bit and I will fix error in 3.6.0. Thanks!

**Comment by yevhenii-pazii** [comment]
Fixed routing, there really was bug, but now all works fine.

**Comment by frickelnix** [comment]
i tried the new release, but i am getting the same error message

**Comment by thecederick** [comment]
Can you provide some more information to I can figure-out what is going wrong. I am interested of cluster info (how many nodes do you have, which version of Rabbit and Erlang do you use), exchange and queue routing structure. It will be grate if you can attach screens from RabbitMQ management.

**Comment by yevhenii-pazii** [comment]
Now I got that you want to say. How does argument works? It "says" to rabbit router that it can't route message, so message don't delivers to queues, then it creates new message and deliver it instead of old one. Erlang and Rabbit disallow modification of existing delivery, it means that only way to get updated message is to send a new one. That's why you get an "Message published, but not routed". It is OK. On real clients you will not get such message.

**Comment by frickelnix** [comment]
ok ... i've got it...thanks

**Comment by akudahewa** [comment]
I have used 3.9.5 release. even that I get Message published but NOT routed when I published the message. If it create new message, where that message goes then. When I read from queue, its empty. Can you share your thoughts.

Thank you

**Comment by FalconerTC** [comment]
Also seeing this on 3.9.5
